### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [uniQueSense/Gra_Kolkokrzyzyk#1]
1. [Nie wolno `import *`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/main.py#L5) (2. rozdział Poradnika).
2. [Luźny kod](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/main.py#L25) włożyć do funkcji `main()` (3. rozdział).
3. [`if wartosc`, `if not wartosc`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/main.py#L65) (2. rozdział). To samo wszędzie.
4. [Kolory nazywać wg zastosowania, nie zawartości](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/main.py#L91) (2. rozdział). W pliku `stale.py` można przy nich dać komentarze, co to za kolory.
5. Z 6 w `main.py` zrobić nazwaną stałą (2. rozdział).
6. [Zbędne nawiasy](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/funkcje_rysujace/klasy.py#L16).
7. [`if self.tekst:`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/funkcje_rysujace/klasy.py#L46) (2. rozdział).
8. [Tu](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/funkcje_rysujace/napisy_przyciski.py#L46) albo używać `True` i `False`, albo nazwać magiczne stałe.
9. [To](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/funkcje_rysujace/napisy_przyciski.py#L24) niedobre, bo żeby tego używać, musi Pan znać magiczne indeksy. Użyć przepisu `Assets` z 3. rozdziału z ponazywanymi tymi tekstami. To samo niżej. [Tu](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/obsluga_ruchow/poruszanie.py#L27) zwracać teksty zamiast indeksów.
10. [`import *`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/funkcje_rysujace/pionki.py#L2) niedobry.
11. [Z 3](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/funkcje_rysujace/pionki.py#L6) zrobić nazwaną stałą (2. rozdział).
12. Skrót w nazwie `spr.py` zły.
13. [Tu](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/obsluga_ruchow/spr.py#L5) pisać `if a == b == c:`.
14. [Te](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/obsluga_ruchow/spr.py#L29) wszystkie if-y skasować. Użyć funkcji `abs(osx1 - osx0)` itp.
15. [`tab`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/daec53c35b6e7783ab7a32e2ac33b8721909adcb/sztuczna_inteligencja/minimax.py#L19) zła nazwa. Nadto pisać po prostu `tab.append((wiersz, kol))`.
16. Gdzie testy? (3. rozdział)

**Comment by uniQueSense** [comment]
Poprawiono błędy. Napisałem testy.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany.
1. [2. rozdział Poradnika: "Proszę używać instrukcji `from ... import ...` wyłącznie do importowania modułów z pakietów, a nie poszczególnych klas, funkcji czy stałych z modułów" — której części tego zdania Pan nie rozumie](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/86510b228d4aa931726e470c13d6e286cced539c/main.py#L5)? Powinno być:
```python
from funkcje_rysujace import napisy_przyciski
from funkcje_rysujace import plansza
from obsluga_ruchow import poruszanie
from obsluga_ruchow import sprawdzanie_ruchow
from stale import stale   # Średni pomysł z tą samą nazwą pakietu i modułu; którąś z nich zmienić.
from sztuczna_inteligencja import minimax

# I potem:
    kogo_ruch = stale.GRACZ
    ...
    plansza = plansza.stwórz_tablicę()  # Tu też zmienić którąś z jednakowych nazw.
    ...
# itd.
```
2. Funkcja `main()` za długa. Proszę wydzielić z niej rozsądne części do innych funkcji w tym samym module i je wywoływać.
3. [Po prostu `ośy, ośx = minimax.minimax_ustawianie(...)[0]`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/86510b228d4aa931726e470c13d6e286cced539c/main.py#L127).
4. [Te `blad...`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/86510b228d4aa931726e470c13d6e286cced539c/funkcje_rysujace/napisy_przyciski.py#L92) ponazywać tak, żeby przy ich używaniu było wiadomo, co znaczą.
5. [To](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/86510b228d4aa931726e470c13d6e286cced539c/funkcje_rysujace/napisy_przyciski.py#L105) napisać raz, na koncu funkcji, a nie 3 razy.
6. [Tu](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/86510b228d4aa931726e470c13d6e286cced539c/funkcje_rysujace/assets.py#L14) zostawić samo `Tekst(...)`, bez `.napisz(okno)`. `assets.Assets.load()` wywoływać raz, z `main()`. Metodę `.napisz(okno)` na odpowiednim obiekcie wywoływać w potrzebnym miejscu w razie potrzeby. Nadto włożyć to do listy:
```python
ZASADY = [
    'Witaj...',
    'Zasady gry:',
    ...,
]

    @staticmethod
    def load():
        Assets.zasady = [
            klasy.Tekst(..., stale.OŚY_INFO + 30 * i, ..., x)
            for i, x in enumerate(ZASADY)]
```
7. [Literówka](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/86510b228d4aa931726e470c13d6e286cced539c/stale/stale.py#L20).
8. [Kolory `RED` i `BLUE` smutne](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/86510b228d4aa931726e470c13d6e286cced539c/stale/stale.py#L82) (3. rozdział).
9. [Do komentarzy używać `#`, nie luźno rzuconych napisów](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/86510b228d4aa931726e470c13d6e286cced539c/stale/stale.py#L78). Zdaje mi się, że pylint zwróciłby Panu na to uwagę.
10. [`or not puste`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/86510b228d4aa931726e470c13d6e286cced539c/sztuczna_inteligencja/minimax.py#L44) (2. rozdział).
11. [Tu](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/86510b228d4aa931726e470c13d6e286cced539c/sztuczna_inteligencja/minimax.py#L55) krotki lepsze od list.
12. [Tu](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/86510b228d4aa931726e470c13d6e286cced539c/sztuczna_inteligencja/minimax.py#L63) jak `k` niepotrzebne, użyć `_`.
13. Testy OK. Proszę je napisać jeszcze do jakiegoś innego modułu/funkcji/klasy i wystarczy.

**Comment by uniQueSense** [comment]
Zastosowałem się do Pańskich uwag, dopisałem kolejne testy.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany. Już tylko kosmetyka. Po wprowadzeniu poniższych poprawek będę mógł zaliczyć Pana projekt.
1. [To](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/f621666a95054c92458b1c22e085d8af5813167f/main.py#L165) wygląda komicznie. Lepiej tak:
```python
a, b, c = spam(
    a, b, c)
```
2. [`.assertNotEqual()`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/f621666a95054c92458b1c22e085d8af5813167f/obsluga_ruchow/poruszanie_test.py#L21). [Tu też](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/f621666a95054c92458b1c22e085d8af5813167f/obsluga_ruchow/sprawdzanie_ruchow_test.py#L59).
3. [`assertEqual()`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/f621666a95054c92458b1c22e085d8af5813167f/obsluga_ruchow/poruszanie_test.py#L31). [Tu też](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/f621666a95054c92458b1c22e085d8af5813167f/obsluga_ruchow/sprawdzanie_ruchow_test.py#L52).
4. [Literówki (brak "u")](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/f621666a95054c92458b1c22e085d8af5813167f/obsluga_ruchow/poruszanie_test.py#L13).
5. [Nie używać `self.os...`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/f621666a95054c92458b1c22e085d8af5813167f/obsluga_ruchow/poruszanie_test.py#L18). Po prostu `self.plansza[1][1] = ...` i niżej `poruszanie.porusz_znak(1, 1, 1, 2, ...)`.
6. [`self.assertTrue(sprawdzanie_ruchow.sprawdz_pola(...)`](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/f621666a95054c92458b1c22e085d8af5813167f/obsluga_ruchow/sprawdzanie_ruchow_test.py#L16).

**Comment by uniQueSense** [comment]
Dziękuję za uwagi. Zostały one przeze mnie poprawione.

**Comment by MarcinCiura** [comment]
1. [Skąd takie wcięcie](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/b91da2bd2f54a03cc6f284ac9a577159a06decca/main.py#L166)? Pylint!
2. [Jeszcze tu](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/b91da2bd2f54a03cc6f284ac9a577159a06decca/obsluga_ruchow/sprawdzanie_ruchow_test.py#L46) i niżej pozbyć się `wyniku`.

**Comment by uniQueSense** [comment]
Zmieniono.

**Comment by MarcinCiura** [comment]
[O, a tu](https://github.com/uniQueSense/Gra_Kolkokrzyzyk/blob/9b5222e0d2c6f1340d8a011c1f2f144b09173519/obsluga_ruchow/poruszanie_test.py#L16)?

**Comment by uniQueSense** [comment]
Przepraszam nie zapisałem zmian. Już poprawione.

**Comment by MarcinCiura** [comment]
LGTM

**Comment by uniQueSense** [comment]
Dziękuję za rady.
